### ISSUE TITLE
SQLSTATE[HY000]: General error: 21 bad parameter or other API misuse` after updating TNTSearch.

### ISSUE THREAD

**Issue by hanspagel** [teamtnt/laravel-scout-tntsearch-driver#129]
Seeing warnings when running tests:

    SQLSTATE[HY000]: General error: 21 bad parameter or other API misuse

Works fine before these updates:

    - Updating teamtnt/tntsearch (v1.0.7 => v1.2.0): Loading from cache
    - Updating teamtnt/laravel-scout-tntsearch-driver (v3.0.4 => v3.0.5): Loading from cache

Latest Laravel, PostgreSQL 10.1. Any ideas?

**Comment by nticaric** [comment]
Any chance you are running php 7.2?

**Comment by hanspagel** [comment]
Exactly, you are right! Forgot to mention it.

**Comment by nticaric** [comment]
#127

**Comment by nticaric** [comment]
Can you try v3.0.6, hopefully it should be fixed

**Comment by hanspagel** [comment]
Fixed! :)))

**Comment by hanspagel** [comment]
Ah, sorry. It's not fixed. Scout was disabled in testing environment. Still the same message with teamtnt/laravel-scout-tntsearch-driver 3.0.6.

**Comment by spacemudd** [comment]
PHP 7.2 here.

This error occurred first when I try to insert 2k+ records into a sqlite db.

Then I started encountering it with TNTSearch.

And I'm now I'm getting sometimes the error when retrieving records using Scout's paginate() method.

I think I'll revert back to 7.1.
